// This parser is generated by PEG.js from `src/parser.peg`.
exports.parser = require("./lib/parser"),

// This is just a convenience thing, so you can call `nagiohdear.parse()`.
exports.parse = exports.parser.parse.bind(exports.parser);

// The generator right now is pretty rudimentary, but for the most part it
// seems to work fine. See [`generator`](generator.html) for more info.
exports.generator = require("./lib/generator");

// Same deal as with `.parse`. Just convenience.
exports.generate = exports.generator.generate.bind(exports.generator);
